### PR TITLE
Super Mutant and other mob updates

### PR DESCRIPTION
**Pull request by Goldrobo**
Adds in a ranged Super Mutant variant and an adjusted assaultron sprite.

## Description
This pull adds in a new Super Mutant sprite, built for ranged combat, as well as the code for its own mob.   In addition, I've adjusted the Assaultron sprite so its easier to see against road tiles.

## Motivation and Context
The ranged mutant was both to create new, possibly harder mobs, and to add variety to existing mobs.

## How Has This Been Tested?
Tested in increments of two: two of these ranged mutants can kill 4 radscorpions before dying, dropping hunting rifle ammo when they do.  

##Screenshots:

mobupdates

## Changelog (necessary)
:cl:
add: New Super Mutant sprites to Supermutant.dmi and Supermutant_dead.dmi
add: adding a new Super Mutant variant to the supermutant.dm
fix: apparently the wastebots.dm lost the code for the assaultron.  This has been rectified.
tweak: gave the assaultron sprite a new green tinge, to better see amid grey tiles
/:cl:

### CODE REVIEW

**Comment by judgex** [comment]
1) please freshen your fork and re-add the robots.dmi changes.

2) Can we see some screenshots, please, so we can discuss this before a merge?  

Thank you.

**Comment by Goldrobo** [comment]
> 2. Can we see some screenshots, please, so we can discuss this before a merge?

Freshen my fork... how?

**Comment by judgex** [comment]
This is a pretty good example of how to update your fork:

https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/

**Comment by Goldrobo** [comment]
Ok I cannot tell if that fixed anything.  

Screenshots will come later once I get the greenlight for the rest.

**Comment by judgex** [comment]
looks like that clears up the conflicts.

**Comment by Goldrobo** [comment]
Ok I think this is everything.  Please look it over to make its all in order.

**Pull request merged**
