### PR TITLE
Makes death more of a penalty

### PR DESCRIPTION
**Pull request by ma44**
## Description

Makes death more of a setback rather than a quite quick respawn timer
Longer time til able to respawn
Replica pods no longer mutate from cabbage
Replica pod takes a lot longer to grow now if they were to be ever spawned in

## Motivation and Context

Makes death more of a setback

## How Has This Been Tested?

Works:tm:
## Changelog (necessary)
:cl: ma44
del: Replica pods are no longer obtainable via mutate cabbage
tweak: Respawn timer is now a lot longer
/:cl:

### CODE REVIEW

**Comment by FlamingDoritos** [comment]
Aren't replica pods unobtainable now?

**Comment by ma44** [comment]
Apparently they were still a thing for cabbage mutation, removed.

**Comment by Celyne-git** [comment]
*1 hour 30* respawn timer? I'm all for making death a bigger deal, but sometimes shit happens and you run into an 18 karat run of bad luck.

**Comment by ma44** [comment]
~~death can just happen when you're unlucky~~

If you want to make a person able to respawn, set their ``timeofdeath`` variable to a couple hours into the future to enable the usage of the respawn verb or start ahelping for a respawn

**Pull request closed without merging**
