### PR TITLE
Bayonets

### PR DESCRIPTION
**Pull request by nokele**
New bayonets for the following guns:

-Laser musket
-AER9
-Assault rifle

Better bayonet for the following gun:

-Mosin nagant

Picture:
https://i.imgur.com/n3vtoBL.png

Compiles and runs locally and so on.

### CODE REVIEW

**Comment by nokele** [comment]
https://i.imgur.com/n3vtoBL.png

**Comment by goodolrusty** [comment]
Hi, you need to run the map merge to have this PR to merge.  Otherwise, youll need to close your PR, update your fork to the freshest version, manually re-add your changes (best way to do if its minor), or use the mapmerge tool.  This cannot be uploaded until then.

**Comment by nokele** [comment]
Had to update map as well because my previous changes to blueprints got deleted for some reason.

**Comment by nokele** [comment]
Bayonets, the way they are right now don't fit in a 32x32 since they are an overlay adding on the already existing gun, which is typically around 32x32.
Only way to fix this would likely be to make completely different sprites for guns with bayonets and change the code for it, which I won't be doing right now considering I don't have a spriter.
I'll be closing this and opening a new PR regarding the map changes soon if you don't mind.

**Comment by Laus4Deus** [comment]
For sure, for sure.

**Pull request closed without merging**
