### PR TITLE
mish-mash PR, sprite/blueprint fix/mapping

### PR DESCRIPTION
**Pull request by Jaaackx**
## Description
Added sprite to file
Fixed AMR BP
Oasis mapping + walled off Commie Bunker

## Motivation and Context
Sprite for object on the ground was missing in the file it needed to be in
AMR BP crafted the wrong gun, was broken.
Did some stuff that got reverted in an earlier PR due to time dilation and not re-merged for Oasis + changed Vault lower half into general Town storage. Changed up a building, improved the Bar.
Commie bunker was free loot, insanely defendable and just let people base in a ridiculously strong massive bunker.

## How Has This Been Tested?
Works now, compiled.
Map has correct areas and no space tiles.

## Changelog (necessary)
just added a sprite to 1 dmi file
Altered the AMR recipe
altered Pahrump.dmm, Oasis + walled off commie bunker

### CODE REVIEW

**Comment by Jaaackx** [comment]
altered another sprite + the object to point to the right sprite

COMPLETELY UNRELATED ADDITION BECAUSE I AM BAD WITH GITHUB: AMR blueprint crafted a broken, unused version of the gun that accepted 50BMG (the super OP ammo). Corrected this.

**Comment by Jaaackx** [comment]
minor mapping changes added

**Comment by Jaaackx** [comment]
ANOTHER mapping change, just added a small hydroponics room to the far NW seeing as the bunker access got removed, player request

**Comment by Jaaackx** [comment]
okay 100% done now

**Comment by jjpark-kb** [comment]
Rule of thumb is that unrelated content should be put in separate PRs due to atomization. 

I can't tell you to do it, but just saying. :)

**Pull request merged**
