### PR TITLE
BoS Rework - Names, Loadouts, removal of Initiate Knight and Scribe, …

### PR DESCRIPTION
**Pull request by Covert0ddity**
…addition of Initiate and Castellan.

Paladin changed to Paladin-Major
Knights changed to Paladins
Initiate Knights changed to Knights
Initiate Scribes changed to Initiates
Addition of a head-knight named Castellan, with their own armor.

Loadouts for most roles! Choices between energy and ballistic weapons.

## Changelog (necessary)
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
yep, THIS is balance

**Comment by deadricklord** [comment]
Covert joins DR2
PA gets buffed, EMP gets nerfed.
BoS gets an excuse to get even more PA adding roles that don't even exist in fallout lore.

Covert's finally getting to live out his brotherhood power fantasy.

**Comment by Celyne-git** [comment]
y'all are literally banned go back to your hole

**Comment by Covert0ddity** [comment]
Balance required.

**Pull request closed without merging**
