### PR TITLE
Legion Base Overhaul

### PR DESCRIPTION
**Pull request by Crumbo**
A complete overhaul to the current Legion base. If people enjoy this, I'll update NCR, and any feedback is most appreciated.

## Description
The location has stayed the same however, everything else has been changed. It has now been loosely based off the Pahrump Valley Winery and given a more Legion aesthetic. Proper slave pens, farming area, kitchen, as well as spawns within the camp itself. Not to say it's perfect off the bat, the equipment provided is worse compared the majority of items able to be gathered.

## Motivation and Context
The base as it currently stands felt very interchangeable to that of the NCR. Nothing about it apart from the flags would make it seem to be a Legion base at all. I decided to try and improve it to the best of my ability.

## Screenshots:

RYQBY69

Birds eye view of the camp

BE4AgIO

A lovely new farm, slave pen and dirty kitchen. All topped off with the walk of shame so those pesky little slaves never forget their place.

Al0brg2

A good legion is a trained legion. Legion training area includes, but is not limited to: Spawns, Dummys, and some _VERY_ special weights.

EgcKflx

Barebones armoury, Centurion's quarter and the good old fight club.

w1JMJQA

Communal bedrooms and showers, because of course.

6kiXw0t

And last but not least, the entrance and Orator's office. (Plus a turn off toward the camp)

## Changelog (necessary)
:cl:
add: Everything listed above in the screenshots
add: Legion's Special Soap
add: Aggressive chair
add: Brain vs. Brawn
del: Old base
/:cl:

### CODE REVIEW

**Comment by Celyne-git** [comment]
It's a great base, and very well-made, but it's too large and military for me- we're intentionally moving the spotlight away from factions and giving them a smaller, more peaceful base is part of that. Unfortunately, I'm going to have to toss my vote towards the current base.

**Comment by Kabramen** [comment]
I disagree with with Celyne, this base fits way better with legion style. Independent  of the objectives the Legion (or even de focus of the server) has, they **are** a extremy military faction, and by lore they woudn't settle in a random mansion but  in a proper place for a camp. Plus, the current base is very similar to the NCR one, and I think we need more variety of buldings.

And I don't believe its large at all, it may looks big but has too open space, and the buildings itself are pretty small, which I think it's the ideal for the legion,

**Comment by Crumbo** [comment]
> It's a great base, and very well-made, but it's too large and military for me- we're intentionally moving the spotlight away from factions and giving them a smaller, more peaceful base is part of that. Unfortunately, I'm going to have to toss my vote towards the current base.

The only thing I'd say makes it remotely military is the fact they have training dummies and two items which are unobtainable any other way (That being the machete sheathe and the spear quiver). But then, the Legion are inherently military orientated and we've never seen them in a diplomatic position. So we don't know what a peaceful camp would ever look like. Since they're bringing recruits, legionnaires, decanii and a centurion, I'd say the men would probably want to train and keep fit daily. I've given them no weaponry that will assist in slaughter, there is really nothing violent in base to use apart from the machetes at the fight cage and a kitchen knife.

I also combined the buildings all in one and seems to be near equal size to the mansion, the slave pens add quite a bit of room but they're far easier to access than the current ones. I spread the buildings out because I want it to feel like a camp, open space doesn't mean wasted so long as it's filled.

**Comment by Cinnamon-BonBon** [comment]
I definitely think it's a better fit than the current Legion base (Multiple smaller buildings with a purpose, rather than one large one that's half useless.)

However, I'm not a fan of the middle building just through the entrance of the base. 
hredtyertgh

With those two fences, you're forced to go through that building, and there's only one door to go through on the East side if you want to get to the rest of base.

Inevitably, players are going to want to make the "Entrance" of the base against the road, not the metal buildings which effectively provides a large barrier between the rest of the world and the camp. 

I'd say that middle building should be made a bit smaller, adding some more open space- or, shift the entire thing to the West by 9~ tiles and delete the tables/crosses out front, to make the buildings feel like the boundaries of camp, rather than having all the dead space between the road and the working "guts" of the camp.

**Comment by Crumbo** [comment]
> I definitely think it's a better fit than the current Legion base (Multiple smaller buildings with a purpose, rather than one large one that's half useless.)
> 
> However, I'm not a fan of the middle building just through the entrance of the base.
> hredtyertgh
> 
> With those two fences, you're forced to go through that building, and there's only one door to go through on the East side if you want to get to the rest of base.
> 
> Inevitably, players are going to want to make the "Entrance" of the base against the road, not the metal buildings which effectively provides a large barrier between the rest of the world and the camp.
> 
> I'd say that middle building should be made a bit smaller, adding some more open space- or, shift the entire thing to the West by 9~ tiles and delete the tables/crosses out front, to make the buildings feel like the boundaries of camp, rather than having all the dead space between the road and the working "guts" of the camp.

You can also either, wirecut the fence, break down the house wall or mine through. I don't think players should begin with a premade perfect entrance, but the fence at the end of the path serves as a beginning point to where to expand protective defense.

Only problem is, you don't want people moving from the road, into one building and then into camp. With old Legion camp you had the liberty of a 5x13 tunnel. I attribute the longer path to them needing more area to build defense. I could shorten the length slightly, but I'd need to do it without harming the aggressive chair. NCR does have a similar problem.

> EDIT: Also, lacks chickens.

Check screenshot 2.

**Comment by Crumbo** [comment]
k6ajCbo

A pretty quick redo that I think looks fine, opens up the area between the distillery and entrance

**Pull request closed without merging**
