### PR TITLE
Updated Pahrump.dmm

### PR DESCRIPTION
**Pull request by Jaaackx**
##Description
Hotfix for some stuff, minor tweaks.
Motivation and Context
NCR fridge ID locked, some posters showing up through walls, two tables on the same tile, lattice placed around Oasis not able to be walked over.

##How Has This Been Tested?
No space tiles, areas not changed.

##Changelog (necessary)
NCR fridge replaced.
Some misc. gym equipment added around.
Posters shouldn't be visible through walls now.
Minor armoury tweaks.
Removed lattice in/around Oasis.
Minor changes to Follower Hospital.
Oasis Armoury changes.
Oasis Citizen housing changes.

NCR CHEM EQUIPMENT REMOVED AGAIN.

### CODE REVIEW

**Comment by Laus4Deus** [comment]
Of course! nd don't forget to freshen your fork

**Comment by Jaaackx** [comment]
Fork updated and it's reachable, yeah. Tables don't block stuff in the corner afaik, Oasis clinic is set up like that.

**Comment by Jaaackx** [comment]
oh fuck wait the den.dm thing isn't supposed to be here

**Comment by Jaaackx** [comment]
closing this till i sort the den stuff, adding sheriff loadouts

**Pull request closed without merging**
