### PR TITLE
Trogs, Tunnelers, and Spore Carriers!

### PR DESCRIPTION
**Pull request by Goldrobo**
This PR add in sprites and code for Tunnelers, Spore Carriers, and Trogs.

## Description
It adds a "tunnelers.dm" to the simple_animals/hostile folder, bringing in mobs sharing that crouched down, humanoid form.  It also adds a "tunnelers.dmi" for accompanying sprites.

crawlers

Trogs are basic and comparable to Feral Ghouls, Spore Carriers only slightly stronger but are expected to blend into green foliage, and tunnelers are even stronger with poisonous claws.

The "tunneler" mobs each have a different, new faction associated, aside from the spore carrier, who  is simply listed as plant.

Theres also some minor tweaks to the Assaultron... until I get around to making a borg variant. 

## Motivation and Context
I've always felt the map is rather limited in mob variety, and this is just one of many on my crusade to diversify the wastes.

The tweaks to the assaultron are purely for roleplay purposes, and are likely to be reverted once appropriate borgs are created.

## How Has This Been Tested?
Tested the assaultron repair function.  Welder tools works fine, and as they're simple mobs, theres no need to use cable coil to repair burns.  Will either be removed once assaultron borgs are made, or adapted to other wastebot mobs.  

The mobs new faction have been tested and are working fine.

## Changelog (necessary)
:cl:
add: tunnelers.dm for new mob types.
add: accompanying tunnelers.dmi for sprites
tweak: given the assaultron the ability to be pulled and be repaired via welding tool.
/:cl:

### CODE REVIEW

**Comment by Laus4Deus** [comment]
Compare their health to the ghouls'

**Comment by Goldrobo** [comment]
They've about as much as a Reaver.  

Is that too much?

**Comment by Laus4Deus** [comment]
Depends on how avaible they will be. If they are confined in a *dungeon* probably not, but if you see them roaming around in the streets, robably yes

**Comment by Goldrobo** [comment]
hm, good point.  The tunnelers at least are SUPPOSED to be tough, and spore carriers are meant to be in dungeons.

I'll make the changes.

**Comment by Goldrobo** [comment]
Ok, does that fix it?

**Comment by Laus4Deus** [comment]
Yeah! One mob that's weak and can be spammed. One mob in the middle and one mob that's strong sounds like a good balance and freedom to make the dungeon. A miniboss surrounded by 4-7 small mobs kind of deal, for example.

**Pull request merged**
