### PR TITLE
Eco test

### PR DESCRIPTION
**Pull request by nokele**
**Changes and stuff**
Alright here are the changes
- Vending machine at shop (sells parts for UZI and R91 for 400 each)
- 4 part spawners scattered throughout the map
- UZI and R91 blueprints at shop

Other unrelated changes
- Uniform and hat for some militia uniform, sprites by Kaleb and someone
- Musket can get bayonet because I was asked to 
- That is all I believe

**Works?**
Compiles and runs locally.

### CODE REVIEW

**Comment by nokele** [comment]
Actually removed RNG for the blueprints. 
Also added Kaleb's suit and hat.

**Comment by goodolrusty** [comment]
Also, this PR conflicts with the hotfix we had to deploy.  The quickest way to address this is to update your fork.  Use the map merge tool, merge your changes into the latest map version, and to add your changes to the recipes.dm to the one that was updated in the hot fix.  Should be very straight forward and take only a couple of minutes.

**Comment by goodolrusty** [comment]
This update also has files that will conflict with the hotfix we had to get through, specifically, use the map merge too and combine your map updates with the latest copy, and also, take your changes from the recipe.dm and put it into the newest version of the file.  First step to this is to update your fork to the latest version.

Also your trying to sneak in and push in changes that no ones agreed with, typically, adding in new things is great, but to remove things its more of a fine-toothed comb vetted process.  The book spawners are fine, and until those changes are reverted, this PR will realistically not be approved for merging.

**Comment by nokele** [comment]
I didn't remove anything though

**Pull request merged**
