### PR TITLE
remove cloning, fixed bluespace gems, changed plasma

### PR DESCRIPTION
**Pull request by PlasticCat**
## Description
Under **Zii**'s order, I am trying to remove cloning 
renamed plasma to ultracite for lore
made bluespace crystals less meme

## Changelog (necessary)
:cl:
edit: changed plasma to ultracite
del: made it so bluespace crystals aren't so memey, renamed them
del: commented out the code for the boards and functions of both the DNA scanner and cloning pod.
/:cl:

### CODE REVIEW

**Comment by Laus4Deus** [comment]
You got a compiling error and the conflic file is because you haven't updated your fork yet.

**Comment by MarinaGryphon** [comment]
Don't do this. Just un-include the files, don't comment the entire file out.

**Comment by PlasticCat** [comment]
Should be ready code daddy

**Comment by Laus4Deus** [comment]
There you go. By commenting out the tech node from techwebs, R&D cannot research the boards to print them but leaves the chance for admins to spawn the boards since the system *exists*

**Comment by judgex** [comment]
I like the way this conversation was resolved - please always leave capabilities intact instead of removing them, just put them out of reach for the playerbase

**Pull request merged**
